"""empty message

Revision ID: ee0f93ec7be5
Revises: 
Create Date: 2021-07-10 19:16:32.948121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee0f93ec7be5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaccine',
    sa.Column('vaccine_id', sa.Integer(), nullable=False),
    sa.Column('vaccine_name', sa.String(length=64), nullable=False),
    sa.Column('produced_company', sa.String(length=64), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=False),
    sa.Column('max_age', sa.Integer(), nullable=False),
    sa.Column('fda_approved', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('vaccine_id')
    )
    op.create_index(op.f('ix_vaccine_vaccine_name'), 'vaccine', ['vaccine_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vaccine_vaccine_name'), table_name='vaccine')
    op.drop_table('vaccine')
    # ### end Alembic commands ###
